x-base:
  base: &base
    build: &build
      context: .
      args: &build-args
        UID: 1000
        GID: 1000
    volumes:
      - .:/workspace

services:
  "3.1":
    <<: *base
    image: rspec-context_helper.rb:3.1
    build:
      <<: *build
      args:
        <<: *build-args
        RUBY_VERSION: 3.1

  "3.0":
    <<: *base
    image: rspec-context_helper.rb:3.0
    build:
      <<: *build
      args:
        <<: *build-args
        RUBY_VERSION: 3.0

  "2.7":
    <<: *base
    image: rspec-context_helper.rb:2.7
    build:
      <<: *build
      args:
        <<: *build-args
        RUBY_VERSION: 2.7
