name: release

on:
  push:
    branches:
      # - main
      - release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          default-branch: release
          release-type: ruby
          # package-name: release-please-demo
          package-name: rspec-context_helper
          bump-minor-pre-major: true
          # version-file: "lib/release/please/demo/version.rb"
          version-file: "lib/rspec/context_helper/version.rb"

      # Checkout code if release was created
      - uses: actions/checkout@v2
        with:
          ref: release
        if: ${{ steps.release.outputs.release_created }}

      # Setup ruby if a release was created
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 3.0.0
          ruby-version: 3.1.2
        if: ${{ steps.release.outputs.release_created }}

      # Bundle install
      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}

      # Publish
      - name: publish gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          ls -l
          # gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
        if: ${{ steps.release.outputs.release_created }}
