name: release

on:
  push:
    branches:
      - release

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Ruby gem

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          default-branch: temp
          release-type: ruby
          package-name: rspec-context_helper
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          version-file: "lib/rspec/context_helper/version.rb"

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}

      - name: push to rubygems.org
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          ls -l
          # gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        if: ${{ steps.release.outputs.release_created }}
